name: Run test on push
on:
  push:
    branches: [ main ]

jobs:
  Run-test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la; pwd; echo "hello"
